shellEmulator: true

trustPolicy: no-downgrade

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@babel/parser': ^7.29.2
  '@babel/types': ^7.29.0
  '@changesets/cli': ^2.30.0
  '@clack/prompts': ^1.1.0
  '@types/node': ^25.5.0
  '@vitest/ui': ^4.1.0
  '@vue/compiler-sfc': ^3.5.30
  cross-spawn: ^7.0.6
  eslint: ^10.1.0
  mri: ^1.2.0
  picocolors: ^1.1.1
  recast: ^0.23.11
  tsdown: ^0.21.4
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^8.0.1
  vitest: ^4.1.0

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
