catalog:
  '@antfu/eslint-config': ^4.16.1
  '@clack/prompts': ^0.11.0
  '@types/node': ^22.15.34
  '@vitest/ui': ^2.1.9
  cross-spawn: ^7.0.6
  eslint: ^9.30.0
  mri: ^1.2.0
  picocolors: ^1.1.1
  recast: ^0.23.11
  tsdown: ^0.12.9
  tsx: ^4.20.3
  typescript: ^5.8.3
  vitest: ^2.1.9

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
