catalog:
  '@antfu/eslint-config': ^6.0.0
  '@babel/parser': ^7.28.4
  '@babel/types': ^7.28.4
  '@clack/prompts': ^0.11.0
  '@types/node': ^22.18.11
  '@vitest/ui': ^3.2.4
  '@vue/compiler-sfc': ^3.5.22
  cross-spawn: ^7.0.6
  eslint: ^9.38.0
  mri: ^1.2.0
  picocolors: ^1.1.1
  recast: ^0.23.11
  tsdown: ^0.15.8
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
