import type { DependencyPresetMap } from './types'
import { dependencyRegistry } from './registry'
import { validateDependencyPresets } from './validator'

export const dependencyPresets = validateDependencyPresets({
  'lang.typescript.base': ['typescript', '@types/node'],
  'lang.typescript.vue': ['typescript', '@types/node', '@vue/tsconfig', 'vue-tsc'],
  'build.vite.base': ['vite'],
  'build.vite.react': ['@vitejs/plugin-react'],
  'build.vite.vue': ['@vitejs/plugin-vue'],
  'project.react.base': ['react', 'react-dom', '@types/react', '@types/react-dom'],
  'project.vue.base': ['vue'],
  'project.hono.base': ['hono'],
  'feature.code-quality.biome': ['@biomejs/biome'],
  'feature.code-quality.prettier': ['prettier', '@trivago/prettier-plugin-sort-imports'],
  'feature.code-quality.oxlint-oxfmt.base': ['oxlint', 'oxfmt'],
  'feature.code-quality.oxlint-oxfmt.type-aware': ['oxlint-tsgolint'],
  'feature.eslint.node.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-n',
    'eslint-plugin-unicorn',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
  ],
  'feature.eslint.node.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-n',
    'eslint-plugin-unicorn',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
    'globals',
  ],
  'feature.eslint.react.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    'eslint-plugin-react-refresh',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
  ],
  'feature.eslint.react.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    'eslint-plugin-react-refresh',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
    'globals',
  ],
  'feature.eslint.vue.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-vue',
    'vue-eslint-parser',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
  ],
  'feature.eslint.vue.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-vue',
    'vue-eslint-parser',
    'eslint-plugin-simple-import-sort',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'typescript-eslint',
    '@eslint/markdown',
    'globals',
  ],
  'feature.eslint-prettier.node.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-n',
    'eslint-plugin-unicorn',
    '@eslint/markdown',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'eslint-config-prettier',
    'typescript-eslint',
  ],
  'feature.eslint-prettier.node.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-n',
    'eslint-plugin-unicorn',
    '@eslint/markdown',
    'eslint-plugin-jsonc',
    'eslint-plugin-yml',
    'eslint-config-prettier',
    'globals',
  ],
  'feature.eslint-prettier.react.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    'eslint-plugin-react-refresh',
    'eslint-plugin-jsx-a11y',
    'eslint-config-prettier',
    'globals',
    'typescript-eslint',
  ],
  'feature.eslint-prettier.react.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    'eslint-plugin-react-refresh',
    'eslint-plugin-jsx-a11y',
    'eslint-config-prettier',
    'globals',
  ],
  'feature.eslint-prettier.vue.typescript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-vue',
    'vue-eslint-parser',
    'eslint-config-prettier',
    'typescript-eslint',
  ],
  'feature.eslint-prettier.vue.javascript': [
    'eslint',
    '@eslint/js',
    'eslint-plugin-vue',
    'vue-eslint-parser',
    'eslint-config-prettier',
    'globals',
  ],
  'feature.css-framework.tailwind.base': ['tailwindcss'],
  'feature.css-framework.tailwind.vite': ['@tailwindcss/vite'],
  'feature.css-framework.unocss.vite': ['unocss'],
  'feature.css-preprocessor.less': ['less'],
  'feature.css-preprocessor.scss': ['sass'],
  'feature.http.axios': ['axios'],
  'feature.http.ky': ['ky'],
  'feature.react.routing.react-router': ['react-router'],
  'feature.react.routing.tanstack-router': ['@tanstack/react-router'],
  'feature.react.routing.wouter': ['wouter'],
  'feature.react.query.react-query': ['@tanstack/react-query'],
  'feature.react.query.swr': ['swr'],
  'feature.react.state.zustand': ['zustand'],
  'feature.react.state.jotai': ['jotai'],
  'feature.react.state.mobx': ['mobx'],
  'feature.react.state.redux': ['@reduxjs/toolkit', 'react-redux'],
  'feature.vue.router': ['vue-router'],
  'feature.vue.state.pinia': ['pinia'],
  'feature.node.runtime.tsx': ['tsx'],
  'feature.node.runtime.ts-node': ['ts-node'],
  'feature.node.runtime.esno': ['esno'],
  'feature.node.webserver.express': ['express'],
  'feature.node.webserver.express.typescript': ['@types/express'],
  'feature.node.webserver.fastify': ['fastify'],
  'feature.node.bundler.tsup': ['tsup', '@swc/core'],
  'feature.node.bundler.tsdown': ['tsdown'],
  'feature.hono.runtime.node': ['@hono/node-server', 'tsx'],
  'feature.hono.runtime.cloudflare-workers': ['wrangler'],
  'feature.hono.validation.zod': ['zod'],
  'feature.hono.validation.valibot': ['valibot'],
  'feature.hono.validation.yup': ['yup'],
  'feature.hono.openapi.zod': ['hono-zod-openapi', 'zod-openapi'],
  'feature.hono.database.prisma': ['prisma', '@prisma/client'],
  'feature.hono.database.drizzle': ['drizzle'],
  'feature.hono.database.kysely': ['kysely'],
  'feature.hono.auth.lucia': ['lucia'],
  'feature.hono.auth.authjs': ['next-auth'],
  'feature.hono.testing.vitest': ['vitest'],
  'feature.hono.testing.jest': ['jest'],
} satisfies DependencyPresetMap, dependencyRegistry)
