import type { ManagedDependency, ManagedDependencyRegistry } from './types'
import { validateDependencyRegistry } from './validator'

function createManagedDependency(config: ManagedDependency) {
  return config
}

const PATCH_ONLY = {
  patch: true,
  minor: false,
  major: false,
} as const

const PATCH_AND_MINOR = {
  patch: true,
  minor: true,
  major: false,
} as const

export const dependencyRegistry = validateDependencyRegistry({
  'typescript': createManagedDependency({
    packageName: 'typescript',
    version: '5.9.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@types/node': createManagedDependency({
    packageName: '@types/node',
    version: '25.5.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  '@vue/tsconfig': createManagedDependency({
    packageName: '@vue/tsconfig',
    version: '0.9.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'vue-tsc': createManagedDependency({
    packageName: 'vue-tsc',
    version: '3.2.6',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'vite': createManagedDependency({
    packageName: 'vite',
    version: '8.0.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@vitejs/plugin-react': createManagedDependency({
    packageName: '@vitejs/plugin-react',
    version: '6.0.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@vitejs/plugin-vue': createManagedDependency({
    packageName: '@vitejs/plugin-vue',
    version: '6.0.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'react': createManagedDependency({
    packageName: 'react',
    version: '19.2.4',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'react-dom': createManagedDependency({
    packageName: 'react-dom',
    version: '19.2.4',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@types/react': createManagedDependency({
    packageName: '@types/react',
    version: '19.2.14',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@types/react-dom': createManagedDependency({
    packageName: '@types/react-dom',
    version: '19.2.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'vue': createManagedDependency({
    packageName: 'vue',
    version: '3.5.32',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'zod': createManagedDependency({
    packageName: 'zod',
    version: '4.3.6',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'valibot': createManagedDependency({
    packageName: 'valibot',
    version: '1.3.1',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'yup': createManagedDependency({
    packageName: 'yup',
    version: '1.7.1',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'prisma': createManagedDependency({
    packageName: 'prisma',
    version: '7.6.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@prisma/client': createManagedDependency({
    packageName: '@prisma/client',
    version: '7.6.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'drizzle': createManagedDependency({
    packageName: 'drizzle',
    version: '1.4.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'kysely': createManagedDependency({
    packageName: 'kysely',
    version: '0.28.15',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'lucia': createManagedDependency({
    packageName: 'lucia',
    version: '3.2.2',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'next-auth': createManagedDependency({
    packageName: 'next-auth',
    version: '4.24.13',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'vitest': createManagedDependency({
    packageName: 'vitest',
    version: '4.1.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'jest': createManagedDependency({
    packageName: 'jest',
    version: '30.1.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'wrangler': createManagedDependency({
    packageName: 'wrangler',
    version: '4.80.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'eslint': createManagedDependency({
    packageName: 'eslint',
    version: '10.2.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@eslint/js': createManagedDependency({
    packageName: '@eslint/js',
    version: '10.0.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@eslint/markdown': createManagedDependency({
    packageName: '@eslint/markdown',
    version: '7.5.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-react': createManagedDependency({
    packageName: 'eslint-plugin-react',
    version: '7.37.5',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'eslint-plugin-react-hooks': createManagedDependency({
    packageName: 'eslint-plugin-react-hooks',
    version: '7.0.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-react-refresh': createManagedDependency({
    packageName: 'eslint-plugin-react-refresh',
    version: '0.5.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-jsx-a11y': createManagedDependency({
    packageName: 'eslint-plugin-jsx-a11y',
    version: '6.10.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-simple-import-sort': createManagedDependency({
    packageName: 'eslint-plugin-simple-import-sort',
    version: '12.1.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-jsonc': createManagedDependency({
    packageName: 'eslint-plugin-jsonc',
    version: '3.1.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-yml': createManagedDependency({
    packageName: 'eslint-plugin-yml',
    version: '3.3.1',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-n': createManagedDependency({
    packageName: 'eslint-plugin-n',
    version: '17.24.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-unicorn': createManagedDependency({
    packageName: 'eslint-plugin-unicorn',
    version: '63.0.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-plugin-vue': createManagedDependency({
    packageName: 'eslint-plugin-vue',
    version: '10.8.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'vue-eslint-parser': createManagedDependency({
    packageName: 'vue-eslint-parser',
    version: '10.4.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'typescript-eslint': createManagedDependency({
    packageName: 'typescript-eslint',
    version: '8.58.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'globals': createManagedDependency({
    packageName: 'globals',
    version: '17.4.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'prettier': createManagedDependency({
    packageName: 'prettier',
    version: '3.5.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@trivago/prettier-plugin-sort-imports': createManagedDependency({
    packageName: '@trivago/prettier-plugin-sort-imports',
    version: '6.0.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'eslint-config-prettier': createManagedDependency({
    packageName: 'eslint-config-prettier',
    version: '10.1.8',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@biomejs/biome': createManagedDependency({
    packageName: '@biomejs/biome',
    version: '2.4.9',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'oxlint': createManagedDependency({
    packageName: 'oxlint',
    version: '1.56.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'oxfmt': createManagedDependency({
    packageName: 'oxfmt',
    version: '0.41.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'oxlint-tsgolint': createManagedDependency({
    packageName: 'oxlint-tsgolint',
    version: '0.19.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'tailwindcss': createManagedDependency({
    packageName: 'tailwindcss',
    version: '4.1.11',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@tailwindcss/vite': createManagedDependency({
    packageName: '@tailwindcss/vite',
    version: '4.1.11',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'unocss': createManagedDependency({
    packageName: 'unocss',
    version: '66.3.3',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'high',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'less': createManagedDependency({
    packageName: 'less',
    version: '4.6.4',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'sass': createManagedDependency({
    packageName: 'sass',
    version: '1.99.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'axios': createManagedDependency({
    packageName: 'axios',
    version: '1.14.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'low',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'ky': createManagedDependency({
    packageName: 'ky',
    version: '1.14.3',
    prefix: '^',
    scope: 'dependencies',
    risk: 'low',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'react-router': createManagedDependency({
    packageName: 'react-router',
    version: '7.14.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  '@tanstack/react-router': createManagedDependency({
    packageName: '@tanstack/react-router',
    version: '1.168.10',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'wouter': createManagedDependency({
    packageName: 'wouter',
    version: '3.9.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@tanstack/react-query': createManagedDependency({
    packageName: '@tanstack/react-query',
    version: '5.96.2',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'swr': createManagedDependency({
    packageName: 'swr',
    version: '2.4.1',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'zustand': createManagedDependency({
    packageName: 'zustand',
    version: '5.0.12',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'jotai': createManagedDependency({
    packageName: 'jotai',
    version: '2.19.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'mobx': createManagedDependency({
    packageName: 'mobx',
    version: '6.15.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@reduxjs/toolkit': createManagedDependency({
    packageName: '@reduxjs/toolkit',
    version: '2.11.2',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'react-redux': createManagedDependency({
    packageName: 'react-redux',
    version: '9.2.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'pinia': createManagedDependency({
    packageName: 'pinia',
    version: '3.0.4',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'vue-router': createManagedDependency({
    packageName: 'vue-router',
    version: '5.0.4',
    prefix: '^',
    scope: 'dependencies',
    risk: 'high',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'minor',
  }),
  'tsx': createManagedDependency({
    packageName: 'tsx',
    version: '4.21.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'ts-node': createManagedDependency({
    packageName: 'ts-node',
    version: '10.9.2',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'esno': createManagedDependency({
    packageName: 'esno',
    version: '4.8.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'express': createManagedDependency({
    packageName: 'express',
    version: '5.1.0',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@types/express': createManagedDependency({
    packageName: '@types/express',
    version: '5.0.6',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'low',
    templateCoupling: 'config',
    autoUpdate: PATCH_AND_MINOR,
    releaseImpact: 'patch',
  }),
  'fastify': createManagedDependency({
    packageName: 'fastify',
    version: '5.3.3',
    prefix: '^',
    scope: 'dependencies',
    risk: 'medium',
    templateCoupling: 'runtime',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'tsup': createManagedDependency({
    packageName: 'tsup',
    version: '8.5.0',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  '@swc/core': createManagedDependency({
    packageName: '@swc/core',
    version: '1.11.31',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
  'tsdown': createManagedDependency({
    packageName: 'tsdown',
    version: '0.12.6',
    prefix: '^',
    scope: 'devDependencies',
    risk: 'medium',
    templateCoupling: 'config',
    autoUpdate: PATCH_ONLY,
    releaseImpact: 'patch',
  }),
} satisfies ManagedDependencyRegistry)
